version: '3'
services:
  postgres:
    container_name: wallet-api-go-postgres
    build:
      context: docker/db
      dockerfile: Dockerfile
    image: wallet-api-go-postgres:latest   
    ports:
      - "5432:5432"